spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alexkovalenko/spring-cloud-learn-config.git

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8082/eureka/