version: "2.1"
services:
  config:
    image: alexkovalenko/config
    ports:
      - "8081:8081"
  discovery:
    image: alexkovalenko/discovery
    ports:
      - "8082:8082"
    links:
      - config
  book-service:
    image: alexkovalenko/book-service
    ports:
      - "8083:8083"
  rating-service:
    image: alexkovalenko/rating-service
    ports:
      - "8084:8084"
  gateway:
    image: alexkovalenko/rating-service
    ports:
      - "8080:8080"
