version: "2.1"
services:
  config:
    build: ./config
    restart: always
    ports:
      - "8081:8081"

  discovery:
    build: ./discovery
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - "8082:8082"

  book-service:
    build: ./book-service
    restart: always
    depends_on:
      discovery:
        condition: service_healthy
    ports:
      - "8083:8083"

  rating-service:
    build: ./rating-service
    restart: always
    depends_on:
      discovery:
        condition: service_healthy
    ports:
      - "8084:8084"

  gateway:
    build: ./gateway
    restart: always
    depends_on:
      discovery:
        condition: service_healthy
    ports:
      - "8080:8080"
